config/routes.rb
Rails.application.routes.draw do
    
    root "pages#home"
    
    get '/home', to: 'pages#home'
    
    resources :recipes do
       member do
          post 'like' 
       end
    end
    
    resources :chefs, except: [:new]
    
    get '/register', to: 'chefs#new'
    
    get '/login', to: 'logins#new'
    post '/login', to: 'logins#create'
    get '/logout', to: 'logins#destroy'
    
    resources :styles, only: [:new, :create, :show]
    resources :ingredients, only: [:new, :create, :show ]
    
    

end

app/views/pages/home.html.erb
<div class="jumbotron center">
    <h1>Welcome to the Recipe Manager</h1>
    
    
    <h2>Store, view and share your recipes with other users in the community.  Comment and rate other users recipes and mark all your favorites to use in your own kitchen!</h2>
    
    <%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success" %>
    
</div>

<div class="row">
    <div class="col-lg-4">
        <h3 class="midrow">
            View Recipes as Guest
        </h3>
        <h2 class="left">Browse and view recipes as a guest and sign up later</h2>
        <p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small" %></p>
    </div>
    <div class="col-lg-4">
        <h3 class="midrow">
            Sign in to your account
        </h3>
        <h2 class="left">Add/update your recipes, create reviews, like/dislike recipes and much much more</h2>
        <p><%= link_to "Log into your account", login_path, class: "btn btn-warning btn-small" %></p>
    </div>
    <div class="col-lg-4">
        <h3 class="midrow">
            View Recipes as Guest
        </h3>
        <h2 class="left">Browse and view recipes as a guest and sign up later</h2>
        <p><%= link_to "Browse Recipe Listings", "", class: "btn btn-warning btn-small" %></p>
    </div>
</div>