config/routes.rb
Rails.application.routes.draw do
    
    root "pages#home"
    
    get '/home', to: 'pages#home'
    
    resources :recipes do
       member do
          post 'like' 
       end
    end
    
    resources :chefs, except: [:new]
    
    get '/register', to: 'chefs#new'
    
    get '/login', to: 'logins#new'
    post '/login', to: 'logins#create'
    get '/logout', to: 'logins#destroy'
    
    resources :styles, only: [:new, :create, :show]
    resources :ingredients, only: [:new, :create, :show ]
    
    

end

app/models/style.rb
class Style < ActiveRecord::Base
    validates :name, presence: true, length: { minimum: 2, maximum: 25 }
    has_many :recipe_styles
    has_many :recipes, through: :recipe_styles
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
   before_action :require_user, except: [:show]
   
   def show
      @style = Style.find(params[:id])
      @recipe = @style.recipes.paginate(page: params[:page], per_page: 6)
   end
   
   def new
      @style = Style.new 
   end
   
   def create
      @style = Style.new(style_params) 
      if @style.save
          flash[:success] = "Style was created succesfully"
          redirect_to recipes_path
      else
         render "new" 
      end
   end
   
      private
         def style_params
            params.require(:style).permit(:name) 
         end
end

app/views/styles/_style.html.erb
<span class="quiet"><%= link_to style.name, style_path(style) %></span>, 

app/views/styles/new.html.erb
<%= render 'shared/page_title', title: "Create a New Style" %>

<%= render 'shared/errors', obj: @style %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @style do |f| %>
        <%= f.label :Name %>
        <%= f.text_field :name %>
        
        <%= f.submit 'Create Style', class: "btn btn-success" %>
        <% end %>
    </div>
</div>

app/views/styles/show.html.erb
<%= render 'shared/page_title_and_paginate_sort', title: "Recipes for: " + @style.name + " Style Cuisine", paginate: @recipe, sort1: "Likes", sort2: "Updated", sort3: "Chef" %>

<ul class="nav nav-tabs">
    <li class="tab-active">
        <%= link_to "Recipes", recipes_path %>
    </li>
    <li>
        <%= link_to "Chefs", chefs_path %>
    </li>
</ul>

<div class="container">
    <% @style.recipes.each do |recipe| %>
        <div class="row">
            <div class="col-md-2">
                <section class="chef_info center">
                    <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
                    <h5>Chef: <%= recipe.chef.chefname %></h5>
                </section>
            </div>
            <div class="col-lg-6 well">
                <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
                <p><%= recipe.summary %></p>
                <p>Style: <%= render recipe.styles %></p>
                <p>Ingredients: <%= render recipe.ingredients %></p>
                <div class="time-stamps pull-left">
                    <p class="created-at"><span class="quiet"><small>created <%= time_ago_in_words(recipe.created_at) %> ago</small></span></p>
                    <p class="updated-at"><span class="quiet"><small>last updated <%= time_ago_in_words(recipe.updated_at) %> ago</small></span></p>
                </div>
                <div class="pull-right thumbs">
                    <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
                        <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
                    <% end %> &nbsp&nbsp&nbsp&nbsp
                    <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
                        <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
                    <% end %>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="col-md-4 center">
                <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
            </div>
        </div>
        <hr class="recipe-hr"/>
    <% end %>
    <div class="row">
        <div class="col-md-4 pull-right paginate">
            <%= will_paginate @recipe %>
        </div>
    </div>
</div>